[DEFAULT]
SECRET_KEY = django-insecure-4s*l!k#$3__k+vao$gsr+ybji#^%k5z8t0+i7teq3=s1jp09%v
DEBUG = True

[POSTGRESQL]
DB_NAME = 
DB_USER = 
DB_PASSWORD =
DB_HOST = 
DB_PORT = 
DATABASE_URL = 

[GOOGLE]
CLIENT_ID = 
CLIENT_SECRET =
; REDIRECT_URI = http://localhost:8000/accounts/google/login/callback/

[EMAIL]
EMAIL_HOST_USER = codekalpa@gmail.com
EMAIL_HOST_PASSWORD = jofc idrj vjlw rmec

[GENAI]
API_KEY = your-genai-api-key-here
CREDENTIALS_FILE_PATH = path-to-your-credentials-file