"""
Django settings for bb4app project.

Generated by 'django-admin startproject' using Django 5.0.4.
"""
from django.contrib.auth.signals import user_logged_in
from django.dispatch import receiver
from django.core.mail import send_mail
from django.conf import settings
import os
from pathlib import Path
import configparser
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load configuration from config.ini
config = configparser.ConfigParser()
config.read(BASE_DIR / 'config.ini')

# Use the environment variable PORT provided by Render, or default to 8000
PORT = os.getenv('PORT', '8000')

ALLOWED_HOSTS = ['bb4-django.onrender.com', 'localhost', '127.0.0.1']

# Quick-start development settings - unsuitable for production
SECRET_KEY ="django-insecure-4s*l!k#$3__k+vao$gsr+ybji#^%k5z8t0+i7teq3=s1jp09%v"


DEBUG = os.getenv('DEBUG', config.get('DEFAULT', 'DEBUG', fallback='True')) == 'True'

# Google OAuth settings
GOOGLE_CLIENT_ID = os.getenv('GOOGLE_CLIENT_ID', config.get('GOOGLE', 'CLIENT_ID', fallback=''))
GOOGLE_CLIENT_SECRET = os.getenv('GOOGLE_CLIENT_SECRET', config.get('GOOGLE', 'CLIENT_SECRET', fallback=''))
SITE_ID = 3

# Application definition
STATIC_URL = "/static/"
STATIC_ROOT = "staticfiles"
INSTALLED_APPS = [ 
    'bb4main',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "django.contrib.sites",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.github",
    'crispy_forms',
]

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
        'APP': {
            'client_id': GOOGLE_CLIENT_ID,
            'secret': GOOGLE_CLIENT_SECRET,       
            'redirect_uri': 'https://bb4-django.onrender.com/accounts/google/login/callback/' if not DEBUG else 'http://localhost:8000/accounts/google/login/callback/',
        }
    },
    # 'github': {
    #     'SCOPE': ['profile', 'email'],
    #     'AUTH_PARAMS': {'access_type': 'online'},
    # }
}

# CSRF settings
CSRF_COOKIE_SECURE = True if not DEBUG else False
CSRF_COOKIE_HTTPONLY = False

CSRF_TRUSTED_ORIGINS = ['https://bb4-django.onrender.com', 'http://localhost:8000']

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',  
]

ROOT_URLCONF = 'bb4app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
            BASE_DIR / 'bb4main' / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bb4app.wsgi.application'

# Database - PostgreSQL with config.ini fallbacks
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': os.getenv('DB_NAME', config.get('POSTGRESQL', 'DB_NAME', fallback='bb4_local_db')),
#         'USER': os.getenv('DB_USER', config.get('POSTGRESQL', 'DB_USER', fallback='bb4_django_pg_user')),
#         'PASSWORD': 'herin',
#         'HOST': os.getenv('DB_HOST', config.get('POSTGRESQL', 'DB_HOST', fallback='localhost')),
#         'PORT': os.getenv('DB_PORT', config.get('POSTGRESQL', 'DB_PORT', fallback='5432')),
#     }
# }

DATABASES = {
    'default': dj_database_url.config(
        default=os.getenv('DATABASE_URL'),
        conn_max_age=600,  # Optional: Keep connections alive for 10 minutes
        ssl_require=True   # Render requires SSL for PostgreSQL
    )
}
# Fallback to local database if DATABASE_URL is not set (for development)
if not os.getenv('DATABASE_URL'):
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'bb4_local_db'),
        'USER': os.getenv('DB_USER', 'bb4_django_pg_user'),
        'PASSWORD': 'herin',  # Replace with your local DB password
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = 'static/'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTHENTICATION_BACKENDS = {
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend"
}

LOGIN_REDIRECT_URL = '/'
LOGIN_URL = '/accounts/login/'
LOGOUT_REDIRECT_URL = "/logout"
SOCIALACCOUNT_LOGIN_ON_GET = True

SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_EMAIL_VERIFICATION = "none"
SOCIALACCOUNT_EMAIL_REQUIRED = True
SOCIALACCOUNT_STORE_TOKENS = True
SOCIALACCOUNT_AUTO_SIGNUP = True

# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = "smtp.gmail.com"
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', config.get('EMAIL', 'EMAIL_HOST_USER', fallback='codekalpa@gmail.com'))
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', config.get('EMAIL', 'EMAIL_HOST_PASSWORD', fallback='jofc idrj vjlw rmec'))
ACCOUNT_EMAIL_VERIFICATION = "none"
ACCOUNT_EMAIL_REQUIRED = True

# # Logging
# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'handlers': {
#         'console': {
#             'class': 'logging.StreamHandler',
#         },
#     },
#     'loggers': {
#         'django': {
#             'handlers': ['console'],
#             'level': 'DEBUG',
#         },
#         'allauth': {
#             'handlers': ['console'],
#             'level': 'DEBUG',
#         },
#     },
# }