# Generated by Django 5.0.4 on 2024-04-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb4main', '0003_fooditem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='name',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='product_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='product_type',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
